[build]
    base = "/"

[[redirects]]
    from = "index.html"
    to = "/"

[[redirects]]
    from = "blog/index.html"
    to = "/blog"

[[redirects]]
    from = "blog/this-is-a-test.html"
    to = "/blog/this-is-a-test"

[[redirects]]
    from = "devlog/index.html"
    to = "/devlog"

[[redirects]]
    from = "devlog/test-dev-log.html"
    to = "/devlog/test-dev-log"

[[redirects]]
    from = "devlog/actix-test.html"
    to = "/devlog/actix-test"

[[redirects]]
    from = "devlog/bitrix-tips.html"
    to = "/devlog/bitrix-tips"